---
- name: Install Java 17 on Debian-based systems
  hosts: openstack_instances
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install OpenJDK 17
      apt:
        name: openjdk-17-jdk
        state: present
